Models/Boissons.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Boissons : Section
    {
        public Boissons()
        {
            Nom = "Boissons";
            Produits = new List<Produit>
            {
                new Produit{ Nom = "Coca-cola 33cl", Prix = 2.00},
                new Produit{ Nom = "Orangina 33cl", Prix = 2.00},
                new Produit{ Nom = "Perrier 33cl", Prix = 1.50},
                new Produit{ Nom = "Vittel 1L", Prix = 1.00},
                new Produit{ Nom = "Leffe Blonde 25cl", Prix = 3.20},
                new Produit{ Nom = "Leffe Ruby 25cl", Prix = 3.20},
            };
        }
    }
}

Models/Carte.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Carte
    {

        public List<Section> Sections { get; set; }

        public Carte()
        {
            Sections = new List<Section> {
                new Entrees(),
                new Plats(),
                new Desserts(),
                new Boissons()
            };
        }
    }
}

Models/Desserts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Desserts : Section
    {
        public Desserts()
        {
            Nom = "Desserts";
            Produits = new List<Produit>
            {
                new Produit{ Nom = "Mousse au chocolat façon Grand-mère", Prix = 4.15},
                new Produit{ Nom = "Banana Splite", Prix = 5.00},
                new Produit{ Nom = "Coupe glâcée", Prix = 5.50},
                new Produit{ Nom = "Café gourmand", Prix = 7.50},
                new Produit{ Nom = "Farandole de desserts", Prix = 9.20},
            };
        }
    }
}

Models/Entrees.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Entrees : Section
    {
        public Entrees(){
            Nom = "Entrées";
            Produits = new List<Produit>
            {
                new Produit{ Nom = "Carpaccio de boeuf", Prix = 11.20},
                new Produit{ Nom = "Tartare de boeuf", Prix = 12.50},
                new Produit{ Nom = "Raviolles au gorgonzola", Prix = 7.50},
                new Produit{ Nom = "Petite salade césar", Prix = 5.20},
            };
        }
    }
}

Models/Plats.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Plats : Section
    {
        public Plats()
        {
            Nom = "Plats";
            Produits = new List<Produit>
            {
                new Produit{ Nom = "Penne aux cambas", Prix = 12.50},
                new Produit{ Nom = "Pizza Capriosa", Prix = 14.00},
                new Produit{ Nom = "Pièce du boucher", Prix = 17.50},
                new Produit{ Nom = "Grande salade César", Prix = 8.20},
                new Produit{ Nom = "Pavé de Saumon à la provencale", Prix = 15.20},
            };
        }
    }
}

Models/Produit.cs
namespace Resto.Models
{
    public class Produit
    {
        public string Nom { get; set; }
        public double Prix { get; set; }

        public Produit() { }
    }
}

Models/Section.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Resto.Models
{
    public class Section
    {
        public string Nom { get; set; }

        public List<Produit> Produits { get; set; }

        public Section()
        {
            Produits = new List<Produit>();
        }
    }
}

ViewModels/CarteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Resto.Models;

namespace Resto.ViewModels
{
    public class CarteViewModel
    {
        public Carte Carte { get; set; }

        public CarteViewModel() { }
    }
}

ViewModels/HomeViewModel.cs
using Resto.Models;

namespace Resto.ViewModels
{
    public class HomeViewModel
    {
        public Carte Carte { get; set; }

        public HomeViewModel() { }
    }
}

Controllers/CarteController.cs
using Resto.Models;
using Resto.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Resto.Controllers
{
    public class CarteController : Controller
    {
        // GET: Carte
        public ActionResult Index()
        {
            var model = new CarteViewModel
            {
                Carte = new Carte()
            };
            return View(model);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Resto.Models;
using Resto.ViewModels;

namespace Resto.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var model = new HomeViewModel
            {
                Carte = new Carte()
            };
            return View(model);
        }
    }
}

Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Resto.Controllers
{
    public class PageController : Controller
    {
        // GET: Page
        public ActionResult Restaurant()
        {
            return View();
        }
    }
}

Views/Carte/Index.cshtml
@model Resto.ViewModels.CarteViewModel
@{
    ViewBag.Title = "Carte";
}

<h1>La carte</h1>

@foreach (var sect in Model.Carte.Sections)
{
    <h2>@sect.Nom</h2>
    <ul>
        @foreach (var produit in sect.Produits)
        {
            <li>@produit.Nom ....................... @produit.Prix€</li>
        }
    </ul>
}

Views/Home/Index.cshtml
@model Resto.ViewModels.HomeViewModel
@{
    ViewBag.Title = "Accueil";
}

<h1>Accueil</h1>

@foreach (var sect in Model.Carte.Sections)
{
    <h2>@sect.Nom</h2>
}

Views/Page/Restaurant.cshtml
@{
    ViewBag.Title = "Restaurant";
}

<h2>Restaurant</h2>

<p>Quel beau restooooo !</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        @Html.ActionLink("O'Resto", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Accueil", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("La carte", "Index", "Carte", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Le restaurant", "Restaurant", "Page", null, new { @class = "nav-link" })
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - O'Resto</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>